### ISSUE TITLE
Dealing with case sensitivity

### ISSUE THREAD

**Issue by placidbits-jon** [mro313/btcgame#1]
https://github.com/mro313/btcgame/blob/8619fdd242488000ca422594a03e0a4d2a56c68f/ConsoleApp1/Program.cs#L64

Instead of putting the work on the user, you can take care of this yourself a couple of ways.

1. Pretty common but not the most efficient. You can just call `ToLower()` on the user input. It could look something like `var input = Console.ReadLine().ToLower();`. This way, you are guaranteed to have a lowercase value when you compare it later
2. You can use [string comparison](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings#case-insensitive-ordinal-comparisons). It would look something like `input.Equals("sell", StringComparison.OrdinalIgnoreCase)`.

**Comment by mro313** [comment]
Opted for the easier method, so to not overload myself. Will be in my next push (lol)
