### ISSUE TITLE
Using a "switch" statement

### ISSUE THREAD

**Issue by placidbits-jon** [mro313/btcgame#3]
https://github.com/mro313/btcgame/blob/8619fdd242488000ca422594a03e0a4d2a56c68f/ConsoleApp1/Program.cs#L68-L71

Once you've gotten the user's input in a variable, the rest of the program is based on the value of that input. Since this one value drives the rest of the logic, you can `switch` on the `input`'s value instead of doing many `if`s. If you complete #2 first, then this would greatly simplify the Program.cs code into something like this:

```
input = Console.ReadLine();

switch (input)
{
  case "sell":
    var seller = new Seller(totalBitcoin, btcPrice);
    seller.SellBitcoin();
    break;

  case "buy":
    var buyer = new Buyer(totalBitcoin, btcPrice);
    buyer.BuyBitcoin(potentialBuyAmount);
    break;

  case "done":
    Console.Clear();
    break;

  default:
    Console.WriteLine("");
}


```

**Comment by mro313** [comment]
Done. @plasmarocker
